export const ADD_TO_CART = 'ADD_TO_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const ACTIVATE_CATEGORY = 'ACTIVATE_CATEGORY';
export const ACTIVATE_PRODUCT = 'ACTIVATE_PRODUCT';